language: go
go:
  # Keep the latest stable release at the top
  # Keep 'tip' just under
  # Because those two Go versions are the ones that interest us the most.
  - "1.15.x"
  - tip
  - "1.14.x"
script: go test -v && go build
before_deploy: "./create_binaries.sh && ls -la /var/tmp/certmin"
deploy:
  provider: releases
  api_key:
    secure: Z54b/IKFIjvItAHSEvJnSeXWyeSb+MljOCF5oRxvoamv4g5gS3PzIZqmPTtJLAxZTd9TvrUVQKg3IJqgiK6js0JH2xTEDonCvOruZ3LBEIoiZQX31I/g7I+uODAfIdBaHanCvuOnTAYKiL4gvfNq1uD0L4SyS9lIRmLxd5DR7aOyfFb+NbpX2PSswRuK1TheWToT8Hn6NpdZPmWTU5bEzMbA4Djo4ec8lhwD/h30GwK5ns0r33dQuwuZzwKwPhI0oWi446LzZaTxVdAV812Llm4jVaL3npbY0ia2H3Gxum8/o4dVkOAzf+k0mhYY2+hU17fjXE5zGAo7Yn8IO/jgHodQ6K36A26a9LgbU4R+07daHrI/9MMxjefwOnOUy82La+7SF8ynQ/ZVakOonvxhCZCgUZDCYbABbQusyazBcTyqN15kyB2Az/hfp06VXqR6jUJWCMK4df/dn5xTo/4NrsEZNM+uXiJsDjRYnVrDLBMXjno9bp8HEvnU27YR94At9PJmcuISKkMw7u3syEJfuVSr2IaRaQlqnoLOA8CPyk1cvpbm9sNVaf5RJcXshNUGBjR4tp9tm47/upUsNzFPzzRazWv63ME8NPfZGk2RMmzONicWM45gm1jJXVmVitJ1uaUEDvpU5yIykmZ3DBV26Rzwqa5k6rReq4Yt8pONEF4=
  file_glob: true
  file: /var/tmp/certmin/*
  skip_cleanup: true
  on:
    repo: nxadm/certmin
    tags: true
    branches:
      only:
      - /^v\d+\.\d+\.\d+$/    
