name: ci
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.15.x, 1.14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Tests
      run: go test -v ./...
    - name: Build lib
      run: go build
    - name: Build cmd
      run: go build
      working-directory: ./cmd/certmin
