name: dev
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: go test -v ./...
    - name: Build
      run: |
        mkdir -p binaries
        export GOOS=linux GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build 
        export GOOS=darwin GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build 
        export GOOS=windows GOARCH=amd64
        echo "Building for $GOOS $GOARCH..."; go build 
        echo "Done"
