name: Development
on: [push, pull_request]
jobs:
  test-build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Test
      run: go test ./...
    - name: Build
      run: |
        mkdir -p binaries
        VERSION=$(git describe --tags)
        GOOS=linux GOARCH=amd64 go build  -o binaries/certmin-linux-amd64
        GOOS=windows GOARCH=amd64 go build -o binaries/certmin-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build -o binaries/certmin-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o binaries/certmin-darwin-arm64
#    - name: Upload linux 64-bit
#      if: startsWith(matrix.go-version,'1.15')
#      uses: actions/upload-artifact@v2
#      with:
#        name: certmin-linux-64bit
#        path: output/lin
#    - name: Upload windows 64-bit
#      if: startsWith(matrix.go-version,'1.15')
#      uses: actions/upload-artifact@v2
#      with:
#        name: certmin-windows-64bit
#        path: output/win
#    - name: Upload darwin 64-bit
#      if: startsWith(matrix.go-version,'1.15')
#      uses: actions/upload-artifact@v2
#      with:
#        name: certmin-darwin-64bit
#        path: output/mac
